# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_qr_handler <- function() {
    .Call(`_anvil_get_qr_handler`)
}

get_qr_handler_cuda <- function() {
    .Call(`_anvil_get_qr_handler_cuda`)
}

