# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit paper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)


## -----------------------------------------------------------------------------
library(stablehlo)
func <- local_func("main")
func
x <- hlo_input("x", "f32", shape = c(2, 2), func = func)
x
y <- hlo_input("y", "f32", shape = c(2, 2), func = func)
y
z <- hlo_multiply(x, y)
z
f <- hlo_return(z)
hlo_string <- repr(f)
hlo_string


## -----------------------------------------------------------------------------
library(pjrt)
x <- pjrt_buffer(1:4, dtype = "f32", device = "cpu")
x
y <- pjrt_buffer(5:8, dtype = "f32", device = "cpu")
y


## -----------------------------------------------------------------------------
program <- pjrt_program(src = hlo_string, format = "mlir")
program
executable <- pjrt_compile(program)
executable


## -----------------------------------------------------------------------------
out <- pjrt_execute(executable, x, y)


## -----------------------------------------------------------------------------
as_array(out)


## -----------------------------------------------------------------------------
library(safetensors)
tmp <- tempfile(fileext = ".safetensors")
safetensors::safe_save_file(list(x = out), tmp, framework = "pjrt")
reloaded <- safetensors::safe_load_file(tmp, framework = "pjrt")
reloaded$x


## -----------------------------------------------------------------------------
library(anvil)
multiply_r <- function(x, y) {
  nv_mul(x, y)
}


## -----------------------------------------------------------------------------
graph <- trace_fn(multiply_r, list(x = nv_scalar(1, "f32"), y = nv_scalar(5, "f32")))
graph


## -----------------------------------------------------------------------------
gradient_graph <- transform_gradient(graph, wrt = c("x", "y"))


## -----------------------------------------------------------------------------
prim("add")[["backward"]]


## -----------------------------------------------------------------------------
out <- stablehlo(graph)
repr(out[[1]])
out[[2]]


## -----------------------------------------------------------------------------
x <- nv_scalar(1, "f32")
x
y <- nv_tensor(1:4, "f32")
y


## -----------------------------------------------------------------------------
multiply_print_r <- function(x, y) {
  print("Hello useR!")
  nv_mul(x, x)
}
multiply_jit <- jit(multiply_print_r)


## -----------------------------------------------------------------------------
multiply_jit(x, y)


## -----------------------------------------------------------------------------
multiply_jit(x, y)


## -----------------------------------------------------------------------------
multiply_jit(nv_scalar(2, "f32"), nv_scalar(3, "f32"))


## -----------------------------------------------------------------------------
multiply_jit(nv_scalar(1, "i32"), nv_scalar(5, "i32"))


## -----------------------------------------------------------------------------
multiply_jit_nested <- jit(function(lst) {
  list(nv_mul(lst[[1]], lst[[2]]))
})
multiply_jit_nested(list(x, y))


## -----------------------------------------------------------------------------
add_or_multiply <- jit(function(x, y, op) {
  if (op == "add") {
    nv_add(x, y)
  } else {
    nv_mul(x, y)
  }
}, static = "op")


## -----------------------------------------------------------------------------
add_or_multiply(x, y, "add")
add_or_multiply(x, y, "multiply")


## -----------------------------------------------------------------------------
add_fn <- function(x, y) {
  nv_add(x, y)
}
grad <- gradient(add_fn, wrt = c("x", "y"))


## -----------------------------------------------------------------------------
x <- nv_scalar(1, "f32")
y <- nv_scalar(5, "f32")
f <- function(x, y) {
  z <- nv_add(x, y)
  grads <- grad(x, z)
  grads
}


## -----------------------------------------------------------------------------
graph <- trace_fn(f, list(x = x, y = y))
graph


## -----------------------------------------------------------------------------
f_jit <- jit(f)
f_jit(x, y)


## -----------------------------------------------------------------------------
multiply_print_r(x, y)


## -----------------------------------------------------------------------------
multiply_print_jit <- jit(function(x, y) {
  out <- nv_mul(x, y)
  nv_print(out)
  return(out)
})
multiply_print_jit(x, y)


## ----eval=FALSE---------------------------------------------------------------
# gen_data <- jit(function(n, p, random_state) {
#   nv_
# })
# n <- 50000L
# p <- 10L
# 
# # Generate features
# X_r <- matrix(rnorm(n * p), nrow = n, ncol = p)
# 
# # True weights
# w_true_r <- rnorm(p) * 0.7
# 
# # Generate binary outcomes using logistic model
# prob <- 1 / (1 + exp(-X_r %*% w_true_r))
# y_r <- rbinom(n, 1, prob)


## -----------------------------------------------------------------------------
p_mul_custom <- AnvilPrimitive("mul_custom")


## -----------------------------------------------------------------------------
nvl_mul_custom <- function(x, y) {
  graph_desc_add(p_mul_custom, list(x, y), infer_fn = infer_binary)[[1L]]
}


## -----------------------------------------------------------------------------
p_mul_custom[["stablehlo"]] <- function(lhs, rhs) {
  list(stablehlo::hlo_multiply(lhs, rhs))
}


## -----------------------------------------------------------------------------
p_mul_custom[["backward"]] <- function(inputs, outputs, grads, required) {
  grad <- grads[[1L]]
  list(
    if (required[[1L]]) nvl_mul(grad, rhs),
    if (required[[2L]]) nvl_mul(grad, lhs)
  )
}

