# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit paper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)


## -----------------------------------------------------------------------------
library(stablehlo)
func <- local_func("main")
func
x <- hlo_input("x", "f32", shape = c(2, 2), func = func)
x
y <- hlo_input("y", "f32", shape = c(2, 2), func = func)
z <- hlo_multiply(x, y)
f <- hlo_return(z)
f
hlo_string <- repr(f)


## -----------------------------------------------------------------------------
library(pjrt)
program <- pjrt_program(src = hlo_string, format = "mlir")


## -----------------------------------------------------------------------------
device <- pjrt_device("cpu")
executable <- pjrt_compile(program, device = device)
executable


## -----------------------------------------------------------------------------
x <- pjrt_buffer(1:4, dtype = "f32", device = "cpu")
x
y <- pjrt_buffer(5:8, dtype = "f32", device = "cpu")
y


## -----------------------------------------------------------------------------
shape(x)
device(x)


## -----------------------------------------------------------------------------
out <- pjrt_execute(executable, x, y)
out


## -----------------------------------------------------------------------------
as_array(out)


## -----------------------------------------------------------------------------
library(safetensors)
tmp <- tempfile(fileext = ".safetensors")
safetensors::safe_save_file(list(x = out), tmp, framework = "pjrt")
reloaded <- safetensors::safe_load_file(tmp, framework = "pjrt")
reloaded$x


## -----------------------------------------------------------------------------
library(quickr)

multiply_r <- function(x, y) {
  declare(
    type(x = double(NA, NA)),
    type(y = double(NA, NA))
  )
  x * y
}
f <- quick(multiply_r)
f(
  matrix(c(1, 2, 3, 4), nrow = 2),
  matrix(c(5, 6, 7, 8), nrow = 2)
)


## -----------------------------------------------------------------------------
library(anvl)
multiply_r <- function(x, y) {
  nv_mul(x, y)
}


## -----------------------------------------------------------------------------
graph <- trace_fn(multiply_r, list(x = nv_scalar(1, "f32"), y = nv_scalar(5, "f32")))
graph


## -----------------------------------------------------------------------------
gradient_graph <- transform_gradient(graph, wrt = c("x", "y"))


## -----------------------------------------------------------------------------
prim_add[["reverse"]]


## -----------------------------------------------------------------------------
out <- stablehlo(graph)
repr(out[[1]])
out[[2]]


## -----------------------------------------------------------------------------
x <- nv_scalar(1, "f32")
x
y <- nv_array(1:4, "f32")
y


## -----------------------------------------------------------------------------
multiply_print_r <- function(x, y) {
  print("Hello useR!")
  nv_mul(x, x)
}
multiply_jit <- jit(multiply_print_r)


## -----------------------------------------------------------------------------
multiply_jit(x, y)


## -----------------------------------------------------------------------------
multiply_jit(x, y)


## -----------------------------------------------------------------------------
multiply_jit(nv_scalar(2, "f32"), nv_scalar(3, "f32"))


## -----------------------------------------------------------------------------
multiply_jit(nv_scalar(1, "i32"), nv_scalar(5, "i32"))


## -----------------------------------------------------------------------------
multiply_jit_nested <- jit(function(lst) {
  list(nv_mul(lst[[1]], lst[[2]]))
})
multiply_jit_nested(list(x, y))


## -----------------------------------------------------------------------------
add_or_multiply <- jit(function(x, y, op) {
  if (op == "add") {
    nv_add(x, y)
  } else {
    nv_mul(x, y)
  }
}, static = "op")


## -----------------------------------------------------------------------------
add_or_multiply(x, y, "add")
add_or_multiply(x, y, "multiply")


## -----------------------------------------------------------------------------
add_fn <- function(x, y) {
  nv_add(x, y)
}
grad <- gradient(add_fn, wrt = c("x", "y"))


## -----------------------------------------------------------------------------
x <- nv_scalar(1, "f32")
y <- nv_scalar(5, "f32")
f <- function(x, y) {
  z <- nv_add(x, y)
  grads <- grad(x, z)
  grads
}


## -----------------------------------------------------------------------------
graph <- trace_fn(f, list(x = x, y = y))
graph


## -----------------------------------------------------------------------------
f_jit <- jit(f)
f_jit(x, y)

