# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit paper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)


## -----------------------------------------------------------------------------
library(stablehlo)
func <- local_func("main")
func
x <- hlo_input("x", "f32", shape = c(2, 2), func = func)
x
y <- hlo_input("y", "f32", shape = c(2, 2), func = func)
y
z <- hlo_multiply(x, y)
z
f <- hlo_return(z)
f
hlo_string <- repr(f)


## -----------------------------------------------------------------------------
library(pjrt)
program <- pjrt_program(src = hlo_string, format = "mlir")


## -----------------------------------------------------------------------------
client <- pjrt_client("cpu")
executable <- pjrt_compile(program, client = client)
executable


## -----------------------------------------------------------------------------
x <- pjrt_buffer(1:4, shape = c(2, 2), dtype = "f32", device = "cpu")
x
y <- pjrt_buffer(5:8, shape = c(2, 2), dtype = "f32", device = "cpu")
y


## -----------------------------------------------------------------------------
shape(x)
device(x)


## -----------------------------------------------------------------------------
out <- pjrt_execute(executable, x, y)
out


## -----------------------------------------------------------------------------
as_array(out)


## -----------------------------------------------------------------------------
library(safetensors)
tmp <- tempfile(fileext = ".safetensors")
safetensors::safe_save_file(list(x = out), tmp, framework = "pjrt")
reloaded <- safetensors::safe_load_file(tmp, framework = "pjrt")
reloaded$x


## -----------------------------------------------------------------------------
library(quickr)

multiply_r <- function(x, y) {
  declare(
    type(x = double(NA, NA)),
    type(y = double(NA, NA))
  )
  x * y
}
f <- quick(multiply_r)
f(
  matrix(c(1, 2, 3, 4), nrow = 2),
  matrix(c(5, 6, 7, 8), nrow = 2)
)


## -----------------------------------------------------------------------------
library(anvil)
multiply_r <- function(x, y) {
  nv_mul(x, y)
}


## -----------------------------------------------------------------------------
graph <- trace_fn(multiply_r, list(x = nv_scalar(1, "f32"), y = nv_scalar(5, "f32")))
graph


## -----------------------------------------------------------------------------
gradient_graph <- transform_gradient(graph, wrt = c("x", "y"))


## -----------------------------------------------------------------------------
prim("add")[["backward"]]


## -----------------------------------------------------------------------------
out <- stablehlo(graph)
repr(out[[1]])
out[[2]]


## -----------------------------------------------------------------------------
x <- nv_scalar(1, "f32")
x
y <- nv_tensor(1:4, "f32")
y


## -----------------------------------------------------------------------------
multiply_print_r <- function(x, y) {
  print("Hello useR!")
  nv_mul(x, x)
}
multiply_jit <- jit(multiply_print_r)


## -----------------------------------------------------------------------------
multiply_jit(x, y)


## -----------------------------------------------------------------------------
multiply_jit(x, y)


## -----------------------------------------------------------------------------
multiply_jit(nv_scalar(2, "f32"), nv_scalar(3, "f32"))


## -----------------------------------------------------------------------------
multiply_jit(nv_scalar(1, "i32"), nv_scalar(5, "i32"))


## -----------------------------------------------------------------------------
multiply_jit_nested <- jit(function(lst) {
  list(nv_mul(lst[[1]], lst[[2]]))
})
multiply_jit_nested(list(x, y))


## -----------------------------------------------------------------------------
add_or_multiply <- jit(function(x, y, op) {
  if (op == "add") {
    nv_add(x, y)
  } else {
    nv_mul(x, y)
  }
}, static = "op")


## -----------------------------------------------------------------------------
add_or_multiply(x, y, "add")
add_or_multiply(x, y, "multiply")


## -----------------------------------------------------------------------------
add_fn <- function(x, y) {
  nv_add(x, y)
}
grad <- gradient(add_fn, wrt = c("x", "y"))


## -----------------------------------------------------------------------------
x <- nv_scalar(1, "f32")
y <- nv_scalar(5, "f32")
f <- function(x, y) {
  z <- nv_add(x, y)
  grads <- grad(x, z)
  grads
}


## -----------------------------------------------------------------------------
graph <- trace_fn(f, list(x = x, y = y))
graph


## -----------------------------------------------------------------------------
f_jit <- jit(f)
f_jit(x, y)


## -----------------------------------------------------------------------------
multiply_print_r(x, y)


## -----------------------------------------------------------------------------
multiply_print_jit <- jit(function(x, y) {
  out <- nv_mul(x, y)
  nv_print(out)
  return(out)
})
multiply_print_jit(x, y)


## -----------------------------------------------------------------------------
set.seed(42)
titanic_df <- as.data.frame(Titanic)
titanic <- titanic_df[rep(seq_len(nrow(titanic_df)), titanic_df$Freq), 1:4]
X <- scale(model.matrix(~ Class + Sex + Age, data = titanic)[, -1])
y <- as.integer(titanic$Survived == "Yes")
n <- nrow(X); p <- ncol(X)

X_tensor <- nv_tensor(X, dtype = "f32")
y_tensor <- nv_tensor(y, dtype = "f32", shape = c(n, 1L))


## -----------------------------------------------------------------------------
model_loss <- function(X, y, beta, alpha) {
  probs <- nv_logistic(X %*% beta + alpha)
  eps <- 1e-7
  probs <- nv_clamp(eps, probs, 1 - eps)
  loss <- -(y * log(probs) + (1 - y) * log(1 - probs))
  mean(loss)
}


## -----------------------------------------------------------------------------
model_loss_grad <- gradient(model_loss, wrt = c("beta", "alpha"))


## -----------------------------------------------------------------------------
fit_logreg <- jit(function(X, y, beta, alpha, n_epochs, lr) {
  output <- nv_while(
    list(beta = beta, alpha = alpha, epoch = nv_scalar(0L)),
    \(beta, alpha, epoch) epoch < n_epochs,
    \(beta, alpha, epoch) {
      grads <- model_loss_grad(X, y, beta, alpha)
      list(
        beta = beta - lr * grads$beta,
        alpha = alpha - lr * grads$alpha,
        epoch = epoch + 1L
      )
    }
  )
  list(beta = output$beta, alpha = output$alpha)
})


## -----------------------------------------------------------------------------
beta_init <- nv_tensor(rnorm(p), dtype = "f32", shape = c(p, 1L))
alpha_init <- nv_scalar(0, dtype = "f32")

result <- fit_logreg(
  X_tensor, y_tensor, beta_init, alpha_init,
  nv_scalar(50000L), nv_scalar(0.1)
)


## ----echo = FALSE-------------------------------------------------------------
glm_fit <- glm(y ~ X, family = binomial)
anvil_coef <- c(as_array(result$alpha), as.vector(as_array(result$beta)))
glm_coef <- coef(glm_fit)
param_names <- gsub("^X", "", names(glm_coef))
comparison <- data.frame(
  Parameter = param_names, anvil = anvil_coef, glm = glm_coef, row.names = NULL
)
comparison


## -----------------------------------------------------------------------------
p_mul_custom <- AnvilPrimitive("mul_custom")


## -----------------------------------------------------------------------------
nvl_mul_custom <- function(x, y) {
  graph_desc_add(p_mul_custom, list(x, y), infer_fn = infer_binary)[[1L]]
}


## ----out.width = "100%"-------------------------------------------------------
p_mul_custom[["stablehlo"]] <- function(lhs, rhs) {
  list(stablehlo::hlo_multiply(lhs, rhs))
}


## -----------------------------------------------------------------------------
p_mul_custom[["backward"]] <- function(inputs, outputs, grads, required) {
  grad <- grads[[1L]]
  list(
    if (required[[1L]]) nvl_mul(grad, rhs),
    if (required[[2L]]) nvl_mul(grad, lhs)
  )
}

