name: Notify r-xla/docker of new release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docker image builds
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DOCKER_REPO_PAT }}
          repository: r-xla/docker
          event-type: anvil-release
          client-payload: '{"tag": "${{ github.event.release.tag_name }}"}'
